const authValidation = {
  // error
  EMAIL_MAX_62_NOT_ALLOW: "EMAIL_MAX_62_NOT_ALLOW",
  FIRSTNAME_NUMBER_NOT_ALLOW: "FIRSTNAME_NUMBER_NOT_ALLOW",
  LASTNAME_NUMBER_NOT_ALLOW: "LASTNAME_NUMBER_NOT_ALLOW",
};
export default authValidation;
