const userValidation = {
  // error
  COMPANYNAME_MAX_60_NOT_ALLOW: "COMPANYNAME_MAX_60_NOT_ALLOW",
  ADDRESS1_MAX_255_NOT_ALLOW: "ADDRESS1_MAX_255_NOT_ALLOW",
  CITY_MAX_40_NOT_ALLOW: "CITY_MAX_40_NOT_ALLOW",
  ZIPCODE_MAX_20_NOT_ALLOW: "ZIPCODE_MAX_20_NOT_ALLOW",
  ABOUTYOURSELF_MAX_5000_NOT_ALLOW: "ABOUTYOURSELF_MAX_5000_NOT_ALLOW",
};

export default userValidation;
